// NiceNagma native gapless loop player (spec §9): a sample-accurate AVAudioEngine
// loop player exposed to Flutter over a MethodChannel (control) and an
// EventChannel (audio-clock position for the matra counter).
//
// This file holds the AppDelegate (plugin registration only) and the LoopPlayer
// class. The channels are wired in SceneDelegate.swift, because Flutter 3.44+
// uses the UIScene lifecycle — the FlutterViewController is created when the
// scene connects, so `window.rootViewController` is nil here in AppDelegate.
// Both files are generated by `flutter create` and already referenced by the
// .pbxproj, so `bootstrap.sh` just overwrites them — no Xcode project surgery.
//
// Why native and not just_audio: the loop WAV from `render/` is already an
// exact-sample-length loop. AVAudioPlayerNode.scheduleBuffer(_:at:options:.loops)
// re-plays that buffer with zero-gap, sample-accurate wraparound — the product's
// non-negotiable "machine-perfect laya" invariant. The UI matra counter is
// driven from the audio clock (playerTime.sampleTime), never a UI timer, so the
// cycle wheel can never drift from the sound.

import AVFoundation
import Flutter
import UIKit

@main
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

// MARK: - LoopPlayer

/// Gapless, sample-accurate loop player for the rendered lehra WAV, plus an
/// independent tanpura drone bus. All audio state is confined here.
final class LoopPlayer: NSObject, FlutterStreamHandler {
  private let engine = AVAudioEngine()
  private let lehra = AVAudioPlayerNode()
  private let tanpura = AVAudioPlayerNode()
  private let tanpuraMixer = AVAudioMixerNode()

  /// Retained so `play()` after a `stop()` can re-schedule the same loop.
  private var lehraBuffer: AVAudioPCMBuffer?
  private var tanpuraBuffer: AVAudioPCMBuffer?

  private var loopFrames: AVAudioFramePosition = 0
  private var sampleRate: Double = 44100
  private var isPlaying = false
  /// True when a loop buffer is queued on `lehra` and ready to start. `stop()`
  /// clears the node's schedule (and its sample clock); we re-arm from sam.
  private var armed = false

  private var eventSink: FlutterEventSink?
  private var positionTimer: Timer?
  /// Last known loop frame; held while paused so the wheel doesn't snap to 0.
  private var lastFrame: AVAudioFramePosition = 0

  init(messenger: FlutterBinaryMessenger) {
    super.init()
    let method = FlutterMethodChannel(name: "nicenagma/loop", binaryMessenger: messenger)
    let events = FlutterEventChannel(name: "nicenagma/loop/position", binaryMessenger: messenger)
    events.setStreamHandler(self)
    configureSession()
    configureEngine()
    // A route change (headphones in/out) or hardware-format change stops the
    // engine and CLEARS every scheduled buffer. Without this we'd go silent
    // and never recover, because our `armed` flag would still claim a loop is
    // queued. See handleConfigChange.
    NotificationCenter.default.addObserver(
      self, selector: #selector(handleConfigChange(_:)),
      name: .AVAudioEngineConfigurationChange, object: engine)
    method.setMethodCallHandler { [weak self] call, result in
      self?.handle(call, result)
    }
  }

  deinit {
    NotificationCenter.default.removeObserver(self)
  }

  /// The engine posts this when the audio route or hardware format changes
  /// (e.g. plugging/unplugging headphones). At this point the engine has
  /// stopped and its scheduled buffers are gone, so our `armed` bookkeeping is
  /// stale. Reset it, restart the engine, and resume on the new route if we
  /// were playing — otherwise the next play() re-arms cleanly on its own.
  @objc private func handleConfigChange(_ note: Notification) {
    DispatchQueue.main.async { [weak self] in
      guard let self = self else { return }
      let wasPlaying = self.isPlaying
      // The node schedules were cleared by the config change; drop our claim.
      self.lehra.stop()
      self.tanpura.stop()
      self.armed = false
      if !self.engine.isRunning { try? self.engine.start() }
      if wasPlaying {
        self.scheduleLehra()
        self.lehra.play()
        if let buf = self.tanpuraBuffer {
          self.tanpura.scheduleBuffer(buf, at: nil, options: .loops, completionHandler: nil)
          self.tanpura.play()
        }
        self.isPlaying = true
      }
    }
  }

  // MARK: Setup

  private func configureSession() {
    let session = AVAudioSession.sharedInstance()
    // .playback keeps sound going with the mute switch on and (with the audio
    // background mode in Info.plist) while the screen is locked.
    try? session.setCategory(.playback, mode: .default)
    try? session.setActive(true)
  }

  private func configureEngine() {
    engine.attach(lehra)
    engine.attach(tanpura)
    engine.attach(tanpuraMixer)
    let fmt = AVAudioFormat(standardFormatWithSampleRate: 44100, channels: 2)
    engine.connect(lehra, to: engine.mainMixerNode, format: fmt)
    engine.connect(tanpura, to: tanpuraMixer, format: fmt)
    engine.connect(tanpuraMixer, to: engine.mainMixerNode, format: fmt)
    tanpuraMixer.outputVolume = 0  // muted until the user raises the mix
    engine.prepare()
  }

  // MARK: Method dispatch

  private func handle(_ call: FlutterMethodCall, _ result: @escaping FlutterResult) {
    switch call.method {
    case "load":
      guard let path = (call.arguments as? [String: Any])?["path"] as? String else {
        result(FlutterError(code: "bad_args", message: "load needs a path", details: nil))
        return
      }
      do {
        try load(path: path)
        result(["loopFrames": loopFrames, "sampleRate": sampleRate])
      } catch {
        result(FlutterError(code: "load_failed", message: error.localizedDescription, details: nil))
      }
    case "play":
      do { try play(); result(nil) }
      catch { result(FlutterError(code: "play_failed", message: error.localizedDescription, details: nil)) }
    case "pause":
      pause(); result(nil)
    case "stop":
      stop(); result(nil)
    case "loadTanpura":
      guard let path = (call.arguments as? [String: Any])?["path"] as? String else {
        result(FlutterError(code: "bad_args", message: "loadTanpura needs a path", details: nil))
        return
      }
      do { try loadTanpura(path: path); result(nil) }
      catch { result(FlutterError(code: "tanpura_failed", message: error.localizedDescription, details: nil)) }
    case "setTanpuraVolume":
      let v = (call.arguments as? [String: Any])?["volume"] as? Double ?? 0
      tanpuraMixer.outputVolume = Float(max(0, min(1, v)))
      result(nil)
    default:
      result(FlutterMethodNotImplemented)
    }
  }

  // MARK: Transport

  /// Load a rendered loop WAV into a PCM buffer and arm it for gapless looping.
  /// Reconnects the player at the file's own format so any sample rate works.
  private func load(path: String) throws {
    let file = try AVAudioFile(forReading: URL(fileURLWithPath: path))
    let fmt = file.processingFormat
    let frames = AVAudioFrameCount(file.length)
    guard frames > 0, let buffer = AVAudioPCMBuffer(pcmFormat: fmt, frameCapacity: frames) else {
      throw NSError(domain: "LoopPlayer", code: 1, userInfo: [NSLocalizedDescriptionKey: "empty audio file"])
    }
    try file.read(into: buffer)

    let wasPlaying = isPlaying
    lehra.stop()
    engine.disconnectNodeOutput(lehra)
    engine.connect(lehra, to: engine.mainMixerNode, format: fmt)

    lehraBuffer = buffer
    loopFrames = file.length
    sampleRate = fmt.sampleRate
    lastFrame = 0
    armed = false

    scheduleLehra()
    if wasPlaying { try play() }  // seamless swap on re-render at a new tempo/key
  }

  /// Queue the loop buffer for gapless, indefinite looping. No-op if already
  /// armed, so play-after-pause never double-schedules.
  private func scheduleLehra() {
    guard let buffer = lehraBuffer, !armed else { return }
    lehra.scheduleBuffer(buffer, at: nil, options: .loops, completionHandler: nil)
    armed = true
  }

  private func play() throws {
    guard lehraBuffer != nil else { return }
    if !engine.isRunning { try engine.start() }
    if !lehra.isPlaying {
      scheduleLehra()  // re-arms only if a prior stop() cleared the schedule
      lehra.play()
    }
    if let buf = tanpuraBuffer, !tanpura.isPlaying {
      tanpura.scheduleBuffer(buf, at: nil, options: .loops, completionHandler: nil)
      tanpura.play()
    }
    isPlaying = true
    startPositionUpdates()
  }

  private func pause() {
    lehra.pause()  // keeps the schedule and position; armed stays true
    tanpura.pause()
    isPlaying = false
    // Keep the timer emitting `lastFrame` so the wheel holds position.
  }

  private func stop() {
    lehra.stop()  // clears the schedule and resets the node's sample clock
    tanpura.stop()
    armed = false
    isPlaying = false
    lastFrame = 0
    scheduleLehra()  // re-arm so the next play() starts from sam
    emit(frame: 0)
  }

  private func loadTanpura(path: String) throws {
    let file = try AVAudioFile(forReading: URL(fileURLWithPath: path))
    let fmt = file.processingFormat
    let frames = AVAudioFrameCount(file.length)
    guard frames > 0, let buffer = AVAudioPCMBuffer(pcmFormat: fmt, frameCapacity: frames) else { return }
    try file.read(into: buffer)
    tanpura.stop()
    engine.disconnectNodeOutput(tanpura)
    engine.connect(tanpura, to: tanpuraMixer, format: fmt)
    tanpuraBuffer = buffer
    if isPlaying {
      tanpura.scheduleBuffer(buffer, at: nil, options: .loops, completionHandler: nil)
      tanpura.play()
    }
  }

  // MARK: Audio-clock position

  /// Current frame within the loop, derived from the audio render clock.
  /// `sampleTime` is monotonic across loop wraps, so modulo gives loop phase.
  private func currentLoopFrame() -> AVAudioFramePosition {
    guard isPlaying,
          let nodeTime = lehra.lastRenderTime,
          let playerTime = lehra.playerTime(forNodeTime: nodeTime),
          loopFrames > 0
    else { return lastFrame }
    let frame = playerTime.sampleTime % loopFrames
    lastFrame = frame < 0 ? 0 : frame
    return lastFrame
  }

  private func startPositionUpdates() {
    guard positionTimer == nil else { return }
    // ~60 Hz. Reads the audio clock each tick — never accumulates, never drifts.
    let timer = Timer(timeInterval: 1.0 / 60.0, repeats: true) { [weak self] _ in
      guard let self = self else { return }
      self.emit(frame: self.currentLoopFrame())
    }
    RunLoop.main.add(timer, forMode: .common)
    positionTimer = timer
  }

  private func emit(frame: AVAudioFramePosition) {
    eventSink?([
      "frame": frame,
      "loopFrames": loopFrames,
      "sampleRate": sampleRate,
      "playing": isPlaying,
    ])
  }

  // MARK: FlutterStreamHandler

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink) -> FlutterError? {
    eventSink = events
    emit(frame: lastFrame)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    eventSink = nil
    return nil
  }
}
