// NiceNagma native gapless loop player (spec §9): a sample-accurate AVAudioEngine
// loop player exposed to Flutter over a MethodChannel (control) and an
// EventChannel (audio-clock position for the matra counter).
//
// This file holds the AppDelegate (plugin registration only), the LoopPlayer
// class, and the OfflineRenderer (on-device render pipeline; MIDI -> mastered loop
// WAV, replacing the Python render service). The channels are wired in
// SceneDelegate.swift, because Flutter 3.44+
// uses the UIScene lifecycle — the FlutterViewController is created when the
// scene connects, so `window.rootViewController` is nil here in AppDelegate.
// Both files are generated by `flutter create` and already referenced by the
// .pbxproj, so `bootstrap.sh` just overwrites them — no Xcode project surgery.
//
// Why native and not just_audio: the loop WAV from `render/` is already an
// exact-sample-length loop. AVAudioPlayerNode.scheduleBuffer(_:at:options:.loops)
// re-plays that buffer with zero-gap, sample-accurate wraparound — the product's
// non-negotiable "machine-perfect laya" invariant. The UI matra counter is
// driven from the audio clock (playerTime.sampleTime), never a UI timer, so the
// cycle wheel can never drift from the sound.

import AVFoundation
import Flutter
import UIKit

@main
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

// MARK: - LoopPlayer

/// Gapless, sample-accurate loop player for the rendered lehra WAV, plus an
/// independent tanpura drone bus. All audio state is confined here.
final class LoopPlayer: NSObject, FlutterStreamHandler {
  private let engine = AVAudioEngine()
  private let lehra = AVAudioPlayerNode()
  private let lehraMixer = AVAudioMixerNode()
  private let tanpura = AVAudioPlayerNode()
  private let tanpuraMixer = AVAudioMixerNode()

  /// Retained so `play()` after a `stop()` can re-schedule the same loop.
  private var lehraBuffer: AVAudioPCMBuffer?
  private var tanpuraBuffer: AVAudioPCMBuffer?

  private var loopFrames: AVAudioFramePosition = 0
  private var sampleRate: Double = 44100
  private var isPlaying = false
  /// True when a loop buffer is queued on `lehra` and ready to start. `stop()`
  /// clears the node's schedule (and its sample clock); we re-arm from sam.
  private var armed = false

  private var eventSink: FlutterEventSink?
  private var positionTimer: Timer?
  /// Last known loop frame; held while paused so the wheel doesn't snap to 0.
  private var lastFrame: AVAudioFramePosition = 0

  init(messenger: FlutterBinaryMessenger) {
    super.init()
    let method = FlutterMethodChannel(name: "nicenagma/loop", binaryMessenger: messenger)
    let events = FlutterEventChannel(name: "nicenagma/loop/position", binaryMessenger: messenger)
    events.setStreamHandler(self)
    configureSession()
    configureEngine()
    // A route change (headphones in/out) or hardware-format change stops the
    // engine and CLEARS every scheduled buffer. Without this we'd go silent
    // and never recover, because our `armed` flag would still claim a loop is
    // queued. See handleConfigChange.
    NotificationCenter.default.addObserver(
      self, selector: #selector(handleConfigChange(_:)),
      name: .AVAudioEngineConfigurationChange, object: engine)
    method.setMethodCallHandler { [weak self] call, result in
      self?.handle(call, result)
    }
  }

  deinit {
    NotificationCenter.default.removeObserver(self)
  }

  /// The engine posts this when the audio route or hardware format changes
  /// (e.g. plugging/unplugging headphones). At this point the engine has
  /// stopped and its scheduled buffers are gone, so our `armed` bookkeeping is
  /// stale. Reset it, restart the engine, and resume on the new route if we
  /// were playing — otherwise the next play() re-arms cleanly on its own.
  @objc private func handleConfigChange(_ note: Notification) {
    DispatchQueue.main.async { [weak self] in
      guard let self = self else { return }
      let wasPlaying = self.isPlaying
      // The node schedules were cleared by the config change; drop our claim.
      self.lehra.stop()
      self.tanpura.stop()
      self.armed = false
      if !self.engine.isRunning { try? self.engine.start() }
      if wasPlaying {
        self.scheduleLehra()
        self.lehra.play()
        if let buf = self.tanpuraBuffer {
          self.tanpura.scheduleBuffer(buf, at: nil, options: .loops, completionHandler: nil)
          self.tanpura.play()
        }
        self.isPlaying = true
      }
    }
  }

  // MARK: Setup

  private func configureSession() {
    let session = AVAudioSession.sharedInstance()
    // .playback keeps sound going with the mute switch on and (with the audio
    // background mode in Info.plist) while the screen is locked.
    try? session.setCategory(.playback, mode: .default)
    try? session.setActive(true)
  }

  private func configureEngine() {
    engine.attach(lehra)
    engine.attach(lehraMixer)
    engine.attach(tanpura)
    engine.attach(tanpuraMixer)
    let fmt = AVAudioFormat(standardFormatWithSampleRate: 44100, channels: 2)
    // Each source gets its own mixer so the UI can set lehra/tanpura volume
    // independently (solo the drone, or blend them at any ratio).
    engine.connect(lehra, to: lehraMixer, format: fmt)
    engine.connect(lehraMixer, to: engine.mainMixerNode, format: fmt)
    // The tanpura WAV is rendered in-tune per Sa, so no pitch shifter is needed.
    engine.connect(tanpura, to: tanpuraMixer, format: fmt)
    engine.connect(tanpuraMixer, to: engine.mainMixerNode, format: fmt)
    tanpuraMixer.outputVolume = 0  // muted until the user raises the mix
    engine.prepare()
  }

  // MARK: Method dispatch

  private func handle(_ call: FlutterMethodCall, _ result: @escaping FlutterResult) {
    switch call.method {
    case "load":
      guard let path = (call.arguments as? [String: Any])?["path"] as? String else {
        result(FlutterError(code: "bad_args", message: "load needs a path", details: nil))
        return
      }
      do {
        try load(path: path)
        result(["loopFrames": loopFrames, "sampleRate": sampleRate])
      } catch {
        result(FlutterError(code: "load_failed", message: error.localizedDescription, details: nil))
      }
    case "play":
      do { try play(); result(nil) }
      catch { result(FlutterError(code: "play_failed", message: error.localizedDescription, details: nil)) }
    case "pause":
      pause(); result(nil)
    case "stop":
      stop(); result(nil)
    case "loadTanpura":
      guard let path = (call.arguments as? [String: Any])?["path"] as? String else {
        result(FlutterError(code: "bad_args", message: "loadTanpura needs a path", details: nil))
        return
      }
      do { try loadTanpura(path: path); result(nil) }
      catch { result(FlutterError(code: "tanpura_failed", message: error.localizedDescription, details: nil)) }
    case "setTanpuraVolume":
      let v = (call.arguments as? [String: Any])?["volume"] as? Double ?? 0
      // Headroom: the tanpura's ceiling sits well below the lehra's so a full drone
      // stays a background reference and never overpowers the lehra.
      tanpuraMixer.outputVolume = Float(max(0, min(1, v)) * 0.55)
      result(nil)
    case "setLehraVolume":
      let v = (call.arguments as? [String: Any])?["volume"] as? Double ?? 1
      lehraMixer.outputVolume = Float(max(0, min(1, v)))
      result(nil)
    default:
      result(FlutterMethodNotImplemented)
    }
  }

  // MARK: Transport

  /// Load a rendered loop WAV into a PCM buffer and arm it for gapless looping.
  /// Reconnects the player at the file's own format so any sample rate works.
  private func load(path: String) throws {
    let file = try AVAudioFile(forReading: URL(fileURLWithPath: path))
    let fmt = file.processingFormat
    let frames = AVAudioFrameCount(file.length)
    guard frames > 0, let buffer = AVAudioPCMBuffer(pcmFormat: fmt, frameCapacity: frames) else {
      throw NSError(domain: "LoopPlayer", code: 1, userInfo: [NSLocalizedDescriptionKey: "empty audio file"])
    }
    try file.read(into: buffer)

    let wasPlaying = isPlaying
    lehra.stop()
    engine.disconnectNodeOutput(lehra)
    engine.connect(lehra, to: lehraMixer, format: fmt)

    lehraBuffer = buffer
    loopFrames = file.length
    sampleRate = fmt.sampleRate
    lastFrame = 0
    armed = false

    scheduleLehra()
    if wasPlaying { try play() }  // seamless swap on re-render at a new tempo/key
  }

  /// Queue the loop buffer for gapless, indefinite looping. No-op if already
  /// armed, so play-after-pause never double-schedules.
  private func scheduleLehra() {
    guard let buffer = lehraBuffer, !armed else { return }
    lehra.scheduleBuffer(buffer, at: nil, options: .loops, completionHandler: nil)
    armed = true
  }

  private func play() throws {
    guard lehraBuffer != nil else { return }
    if !engine.isRunning { try engine.start() }
    if !lehra.isPlaying {
      scheduleLehra()  // re-arms only if a prior stop() cleared the schedule
      lehra.play()
    }
    if let buf = tanpuraBuffer, !tanpura.isPlaying {
      tanpura.scheduleBuffer(buf, at: nil, options: .loops, completionHandler: nil)
      tanpura.play()
    }
    isPlaying = true
    startPositionUpdates()
  }

  private func pause() {
    lehra.pause()  // keeps the schedule and position; armed stays true
    tanpura.pause()
    isPlaying = false
    // Keep the timer emitting `lastFrame` so the wheel holds position.
  }

  private func stop() {
    lehra.stop()  // clears the schedule and resets the node's sample clock
    tanpura.stop()
    armed = false
    isPlaying = false
    lastFrame = 0
    scheduleLehra()  // re-arm so the next play() starts from sam
    emit(frame: 0)
  }

  private func loadTanpura(path: String) throws {
    let file = try AVAudioFile(forReading: URL(fileURLWithPath: path))
    let fmt = file.processingFormat
    let frames = AVAudioFrameCount(file.length)
    guard frames > 0, let buffer = AVAudioPCMBuffer(pcmFormat: fmt, frameCapacity: frames) else { return }
    try file.read(into: buffer)
    tanpura.stop()
    engine.disconnectNodeOutput(tanpura)
    engine.connect(tanpura, to: tanpuraMixer, format: fmt)
    tanpuraBuffer = buffer
    if isPlaying {
      tanpura.scheduleBuffer(buffer, at: nil, options: .loops, completionHandler: nil)
      tanpura.play()
    }
  }

  // MARK: Audio-clock position

  /// Current frame within the loop, derived from the audio render clock.
  /// `sampleTime` is monotonic across loop wraps, so modulo gives loop phase.
  private func currentLoopFrame() -> AVAudioFramePosition {
    guard isPlaying,
          let nodeTime = lehra.lastRenderTime,
          let playerTime = lehra.playerTime(forNodeTime: nodeTime),
          loopFrames > 0
    else { return lastFrame }
    let frame = playerTime.sampleTime % loopFrames
    lastFrame = frame < 0 ? 0 : frame
    return lastFrame
  }

  private func startPositionUpdates() {
    guard positionTimer == nil else { return }
    // ~60 Hz. Reads the audio clock each tick — never accumulates, never drifts.
    let timer = Timer(timeInterval: 1.0 / 60.0, repeats: true) { [weak self] _ in
      guard let self = self else { return }
      self.emit(frame: self.currentLoopFrame())
    }
    RunLoop.main.add(timer, forMode: .common)
    positionTimer = timer
  }

  private func emit(frame: AVAudioFramePosition) {
    eventSink?([
      "frame": frame,
      "loopFrames": loopFrames,
      "sampleRate": sampleRate,
      "playing": isPlaying,
    ])
  }

  // MARK: FlutterStreamHandler

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink) -> FlutterError? {
    eventSink = events
    emit(frame: lastFrame)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    eventSink = nil
    return nil
  }
}

// MARK: - OfflineRenderer

// On-device offline render: Standard MIDI File -> mastered, gapless loop WAV.
//
// This replaces the Python `render/` service for on-device playback. It is the
// native half of the port (the Dart half — parse/compile/midi — produces the SMF
// this consumes). Exposed to Flutter over a MethodChannel; the app selects it via
// LocalRenderer (see lib/services/local_renderer.dart).
//
// Pipeline (mirrors render/master.py, re-tuned for Apple's sampler):
//   AVAudioUnitSampler(sf2) + AVAudioSequencer(SMF) -> offline render (+ a native
//   room reverb) -> seam-wrap (folds release + reverb tail onto the head so the
//   loop is gapless) -> bellows LFO -> double-reed chorus -> peak normalize -> WAV.
//
// Why the machine-perfect-laya invariant still holds: the output is trimmed to
// exactly `loopLengthSamples`, and LoopPlayer loops that exact-length buffer —
// independent of any sub-ms sampler scheduling jitter on interior onsets.

final class OfflineRenderer {
  init(messenger: FlutterBinaryMessenger) {
    let channel = FlutterMethodChannel(name: "nicenagma/render", binaryMessenger: messenger)
    channel.setMethodCallHandler { call, result in
      guard call.method == "render" else { result(FlutterMethodNotImplemented); return }
      guard let a = call.arguments as? [String: Any],
            let midiPath = a["midiPath"] as? String,
            let sfPath = a["soundfontPath"] as? String,
            let outPath = a["outPath"] as? String,
            let sr = a["sampleRate"] as? Int,
            let loopSamples = a["loopLengthSamples"] as? Int
      else {
        result(FlutterError(code: "bad_args", message: "render missing args", details: nil))
        return
      }
      let bellowsRate = a["bellowsRateHz"] as? Double ?? 0.25
      let bellowsDepth = a["bellowsDepth"] as? Double ?? 0.09
      // Plucked instruments (tanpura) skip the harmonium bellows/chorus and use a
      // wider seam-fold (long pluck ring at the wrap) + gentler reverb.
      let pluck = a["pluck"] as? Bool ?? false
      let chorusWet = a["chorusWet"] as? Double ?? 0.2

      DispatchQueue.global(qos: .userInitiated).async {
        do {
          let frames = try OfflineRenderer.render(
            midiPath: midiPath, soundfontPath: sfPath, outPath: outPath,
            sampleRate: Double(sr), loopLengthSamples: loopSamples,
            bellowsRateHz: bellowsRate, bellowsDepth: bellowsDepth,
            pluck: pluck, chorusWet: chorusWet)
          DispatchQueue.main.async { result(frames) }
        } catch {
          DispatchQueue.main.async {
            result(FlutterError(code: "render_failed",
                                message: error.localizedDescription, details: nil))
          }
        }
      }
    }
  }

  // MARK: Mastering tunables (re-tune by ear vs. the fluidsynth reference)

  private static let maxWrapS = 0.6           // seam-wrap window (release + reverb tail)
  private static let tailS = 0.9              // extra frames rendered past the loop end
  private static let reverbWetDryMix: Float = 12.0  // percent; native room presence
  private struct ChorusVoice { let baseMs, depthMs, rateHz, phase: Double }
  private static let chorusVoices = [
    ChorusVoice(baseMs: 12.0, depthMs: 2.5, rateHz: 0.7, phase: 0.0),
    ChorusVoice(baseMs: 19.0, depthMs: 3.0, rateHz: 1.1, phase: 1.7),
  ]

  enum RenderError: Error, LocalizedError {
    case badFormat, noChannelData
    var errorDescription: String? {
      switch self {
      case .badFormat: return "could not create the stereo render format"
      case .noChannelData: return "render buffer had no float channel data"
      }
    }
  }

  // MARK: Render

  static func render(
    midiPath: String, soundfontPath: String, outPath: String,
    sampleRate: Double, loopLengthSamples: Int,
    bellowsRateHz: Double, bellowsDepth: Double,
    pluck: Bool = false, chorusWet chorusWetArg: Double = 0.2
  ) throws -> Int {
    // Pluck preset (tanpura): render the full pluck ring past the loop end and fold
    // it back CIRCULARLY (not a short fade) so the drone density is identical at the
    // loop point — a truly periodic, gapless loop. A soft reverb wash blends the
    // plucks so they read as a sustained pedal rather than firm individual strokes.
    let tailS = pluck ? 10.0 : OfflineRenderer.tailS
    let maxWrapS = pluck ? 0.0 : OfflineRenderer.maxWrapS
    let reverbMix: Float = pluck ? 24.0 : reverbWetDryMix
    let chorusWet = pluck ? 0.0 : chorusWetArg

    let engine = AVAudioEngine()
    let sampler = AVAudioUnitSampler()
    let reverb = AVAudioUnitReverb()
    reverb.loadFactoryPreset(.mediumRoom)
    reverb.wetDryMix = reverbMix

    engine.attach(sampler)
    engine.attach(reverb)
    guard let fmt = AVAudioFormat(standardFormatWithSampleRate: sampleRate, channels: 2) else {
      throw RenderError.badFormat
    }
    engine.connect(sampler, to: reverb, format: fmt)
    engine.connect(reverb, to: engine.mainMixerNode, format: fmt)

    try sampler.loadSoundBankInstrument(
      at: URL(fileURLWithPath: soundfontPath), program: 0,
      bankMSB: UInt8(kAUSampler_DefaultMelodicBankMSB),
      bankLSB: UInt8(kAUSampler_DefaultBankLSB))

    let sequencer = AVAudioSequencer(audioEngine: engine)
    try sequencer.load(from: URL(fileURLWithPath: midiPath), options: [])
    for track in sequencer.tracks { track.destinationAudioUnit = sampler }

    let maxFrames: AVAudioFrameCount = 4096
    try engine.enableManualRenderingMode(.offline, format: fmt, maximumFrameCount: maxFrames)
    try engine.start()
    sequencer.prepareToPlay()
    try sequencer.start()

    let tail = Int(tailS * sampleRate)
    let total = loopLengthSamples + tail
    var left = [Float](); left.reserveCapacity(total)
    var right = [Float](); right.reserveCapacity(total)

    guard let buffer = AVAudioPCMBuffer(pcmFormat: engine.manualRenderingFormat,
                                        frameCapacity: maxFrames) else {
      throw RenderError.badFormat
    }

    var rendered = 0
    while rendered < total {
      let need = AVAudioFrameCount(min(Int(maxFrames), total - rendered))
      let status = try engine.renderOffline(need, to: buffer)
      guard status == .success || status == .insufficientDataFromInputNode else { break }
      let n = Int(buffer.frameLength)
      if n == 0 { break }
      guard let ch = buffer.floatChannelData else { throw RenderError.noChannelData }
      let l = ch[0]
      let r = buffer.format.channelCount > 1 ? ch[1] : ch[0]
      for i in 0..<n { left.append(l[i]); right.append(r[i]) }
      rendered += n
    }
    sequencer.stop()
    engine.stop()

    var (bodyL, bodyR) = seamWrap(left, right, n: loopLengthSamples,
                                  sampleRate: sampleRate, maxWrapS: maxWrapS,
                                  circular: pluck)
    applyBellows(&bodyL, &bodyR, sampleRate: sampleRate,
                 rateHz: bellowsRateHz, depth: bellowsDepth)
    if chorusWet > 0 { applyChorus(&bodyL, &bodyR, sampleRate: sampleRate, wet: chorusWet) }
    normalize(&bodyL, &bodyR)

    try writeWav(bodyL, bodyR, outPath: outPath, sampleRate: sampleRate)
    return bodyL.count
  }

  // MARK: DSP (ports of render/master.py)

  /// Trim to exactly n and fold the natural overhang (release + reverb + pluck
  /// ring) back onto the head so the loop is gapless. `circular` (drones): add the
  /// ENTIRE overhang back modulo n at full level, so a note ringing past the loop
  /// end reappears at the start exactly as an infinite loop would — the density is
  /// identical at the seam. Otherwise (lehra): an equal-power fade over maxWrapS.
  private static func seamWrap(_ left: [Float], _ right: [Float], n: Int,
                               sampleRate: Double, maxWrapS: Double,
                               circular: Bool = false) -> ([Float], [Float]) {
    var bodyL = [Float](repeating: 0, count: n)
    var bodyR = [Float](repeating: 0, count: n)
    let m = left.count
    let copy = min(m, n)
    for i in 0..<copy { bodyL[i] = left[i]; bodyR[i] = right[i] }
    if m > n {
      if circular {
        for j in n..<m {
          let k = (j - n) % n
          bodyL[k] += left[j]
          bodyR[k] += right[j]
        }
      } else {
        let wrap = min(m - n, Int(maxWrapS * sampleRate), n)
        let denom = Double(max(1, wrap - 1))
        for i in 0..<wrap {
          let c = cos(Double(i) / denom * .pi / 2)
          let fade = Float(c * c)
          bodyL[i] += left[n + i] * fade
          bodyR[i] += right[n + i] * fade
        }
      }
    }
    return (bodyL, bodyR)
  }

  /// Slow gain undulation, snapped to a whole number of cycles across the loop.
  private static func applyBellows(_ bodyL: inout [Float], _ bodyR: inout [Float],
                                   sampleRate: Double, rateHz: Double, depth: Double) {
    guard depth > 0 else { return }
    let n = bodyL.count
    let loopS = Double(n) / sampleRate
    let cycles = max(1, Int((rateHz * loopS).rounded()))
    for i in 0..<n {
      let t = Double(i) / sampleRate
      let lfo = (1.0 - depth) + depth * (0.5 + 0.5 * sin(2 * .pi * Double(cycles) / loopS * t))
      let g = Float(lfo)
      bodyL[i] *= g; bodyR[i] *= g
    }
  }

  /// Double-reed shimmer via modulated fractional delay (chorus), read circularly
  /// so the loop stays exact-length and seamless; each LFO runs whole cycles.
  private static func applyChorus(_ bodyL: inout [Float], _ bodyR: inout [Float],
                                  sampleRate: Double, wet chorusWet: Double) {
    let n = bodyL.count
    var chL = [Float](repeating: 0, count: n)
    var chR = [Float](repeating: 0, count: n)
    for v in chorusVoices {
      let cycles = max(1, Int((v.rateHz * (Double(n) / sampleRate)).rounded()))
      for i in 0..<n {
        let lfo = sin(2 * .pi * Double(cycles) * Double(i) / Double(n) + v.phase)
        let delay = (v.baseMs + v.depthMs * lfo) * sampleRate / 1000.0
        var read = (Double(i) - delay).truncatingRemainder(dividingBy: Double(n))
        if read < 0 { read += Double(n) }
        let i0 = Int(read)
        let frac = Float(read - Double(i0))
        let i1 = (i0 + 1) % n
        chL[i] += bodyL[i0] * (1 - frac) + bodyL[i1] * frac
        chR[i] += bodyR[i0] * (1 - frac) + bodyR[i1] * frac
      }
    }
    let vn = Float(chorusVoices.count)
    let wet = Float(chorusWet)
    for i in 0..<n {
      bodyL[i] = (1 - wet) * bodyL[i] + wet * (chL[i] / vn)
      bodyR[i] = (1 - wet) * bodyR[i] + wet * (chR[i] / vn)
    }
  }

  /// Peak-normalize to -1 dBFS (render/master.py's fallback path; true LUFS deferred).
  private static func normalize(_ bodyL: inout [Float], _ bodyR: inout [Float]) {
    var peak: Float = 0
    for i in 0..<bodyL.count {
      peak = max(peak, abs(bodyL[i]), abs(bodyR[i]))
    }
    if peak <= 0 { return }
    let target = Float(pow(10.0, -1.0 / 20.0))
    let g = target / peak
    for i in 0..<bodyL.count { bodyL[i] *= g; bodyR[i] *= g }
  }

  // MARK: WAV out

  private static func writeWav(_ bodyL: [Float], _ bodyR: [Float],
                               outPath: String, sampleRate: Double) throws {
    let settings: [String: Any] = [
      AVFormatIDKey: kAudioFormatLinearPCM,
      AVSampleRateKey: sampleRate,
      AVNumberOfChannelsKey: 2,
      AVLinearPCMBitDepthKey: 16,
      AVLinearPCMIsFloatKey: false,
      AVLinearPCMIsBigEndianKey: false,
      AVLinearPCMIsNonInterleaved: false,
    ]
    let url = URL(fileURLWithPath: outPath)
    try? FileManager.default.removeItem(at: url)
    let file = try AVAudioFile(forWriting: url, settings: settings)
    let n = bodyL.count
    guard let buf = AVAudioPCMBuffer(pcmFormat: file.processingFormat,
                                     frameCapacity: AVAudioFrameCount(n)) else {
      throw RenderError.badFormat
    }
    buf.frameLength = AVAudioFrameCount(n)
    guard let ch = buf.floatChannelData else { throw RenderError.noChannelData }
    for i in 0..<n { ch[0][i] = bodyL[i]; ch[1][i] = bodyR[i] }
    try file.write(from: buf)
  }
}
